# Generated by Django 5.0.7 on 2024-11-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0003_remove_profile_remember_me_alter_profile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingSystems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
    ]
