# Generated by Django 5.0.7 on 2024-11-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0004_farmingsystems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmingsystems',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
