# Generated by Django 5.0.6 on 2024-11-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0004_quotation'),
        ('freshlyapp', '0005_alter_farmingsystems_name'),
    ]

    operations = [
    ]
