# Generated by Django 5.0.6 on 2024-11-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0008_paymentmethod_mpesadetails_creditcarddetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='method',
        ),
    ]
