# Generated by Django 5.0.6 on 2024-11-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0012_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
