# Generated by Django 5.0.6 on 2024-11-10 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0013_order_expected_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='freshlyapp.transporter'),
        ),
    ]
