# Generated by Django 5.0.6 on 2024-11-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0015_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='total_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transporter',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transporter',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
