# Generated by Django 5.0.7 on 2024-11-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0016_transporter_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmingsystems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/FarmingSystems'),
        ),
        migrations.AddField(
            model_name='farmingsystems',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farmingsystems',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
