# Generated by Django 5.0.7 on 2024-11-20 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0017_farmingsystems_image_farmingsystems_in_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenSystems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=400)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='farmingsystems',
            name='image',
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='freshlyapp.poll'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FarmingSystemImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/FarmingSystems')),
                ('farmingsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='freshlyapp.farmingsystems')),
            ],
        ),
        migrations.CreateModel(
            name='GardenSystemImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/GardenSystems')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gardensystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='freshlyapp.gardensystems')),
            ],
        ),
    ]
