# Generated by Django 5.0.7 on 2024-11-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0018_gardensystems_remove_farmingsystems_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardensystems',
            name='description',
            field=models.TextField(max_length=350),
        ),
    ]
