# Generated by Django 5.1.1 on 2024-11-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0020_farmer_address_farmer_farm_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total income of the farmer', max_digits=15),
        ),
        migrations.AddField(
            model_name='farmer',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total sales of the farmer', max_digits=15),
        ),
    ]
