# Generated by Django 5.1.1 on 2024-11-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshlyapp', '0023_orderitem_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_qtty',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='used_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
