runtime: python39

entrypoint: gunicorn --timeout 120 -b :$PORT freshly_set.wsgi --worker-class gevent --workers 3 --worker-connections 1000


service_account: vast-cogency-439407-s4@appspot.gserviceaccount.com


handlers:
- url: /static
  static_dir: staticfiles

- url: /.*
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: "freshly_set.settings"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

inbound_services:
- warmup

instance_class: F2

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10
